spring.application.name=backend


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/testproject
spring.datasource.username=root
spring.datasource.password=password
invoice.upi.vpa=r.navin9508@okaxis